name: Release System

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
      - run: npm run pack
      - run: npm run build

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'system.json'
          prop_path: 'version'

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: Release ${{ steps.version.outputs.prop }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './latest.zip, ./system.json'
          tag: ${{ steps.version.outputs.prop }}
